# Generated by Django 4.2.2 on 2023-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('male', models.BooleanField(blank=True, default=False, null=True)),
                ('female', models.BooleanField(blank=True, default=False, null=True)),
                ('name_of_next_of_kin', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('school_of_origin', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('special_needs', models.BooleanField(blank=True, default=False, null=True)),
                ('specify', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
