# Generated by Django 4.2.2 on 2023-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member_details',
            options={'verbose_name_plural': 'Member details'},
        ),
        migrations.AddField(
            model_name='member_details',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
