# Generated by Django 4.2.2 on 2023-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_details_options_member_details_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='sport_photos')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='member_details',
            options={'ordering': ('firstname',), 'verbose_name_plural': 'Member details'},
        ),
        migrations.RemoveField(
            model_name='member_details',
            name='female',
        ),
        migrations.RemoveField(
            model_name='member_details',
            name='male',
        ),
        migrations.AddField(
            model_name='member_details',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='member_details',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports'),
        ),
    ]
