# Generated by Django 4.2.2 on 2023-08-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_member_details_school_of_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sports_details',
            options={'ordering': ('name',), 'verbose_name_plural': 'Sports details'},
        ),
        migrations.AlterField(
            model_name='member_details',
            name='relationship',
            field=models.CharField(choices=[('guardian', 'Guardian'), ('mother', 'Mother'), ('father', 'Father')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='member_details',
            name='school_of_origin',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='patron_pic')),
                ('about', models.TextField(default='write about the patron')),
                ('patron_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sports_details')),
            ],
        ),
    ]
