# Generated by Django 4.2.2 on 2023-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sports_details_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='item_photo')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('Stock_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patron',
            options={'ordering': ('firstname',)},
        ),
    ]
