# Generated by Django 4.2.2 on 2023-08-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_store_alter_patron_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('stock_available',), 'verbose_name_plural': 'Store'},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Stock_available',
            new_name='stock_available',
        ),
    ]
