# Generated by Django 4.2.2 on 2023-08-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('item_name',), 'verbose_name_plural': 'Store'},
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photo'),
        ),
    ]
