# Generated by Django 4.2.4 on 2023-08-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_store_options_alter_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports_details',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='sporty'),
        ),
    ]
