# Generated by Django 4.2.4 on 2023-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sports_details_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_details',
            name='height',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='member_details',
            name='weight',
            field=models.FloatField(default=50),
        ),
    ]
